name: samsarajoga
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15132
title: Samsára Joga Centrum Košice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ad0132'
    - '#7d4082'
    - '#dc5f13'
    - '#af8ab2'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
